apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: "in-cluster"
      namespace: '*'
  sourceRepos:
    - '*'
