apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minecraft
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: minecraft
      name: "in-cluster"
  sourceRepos:
    - "*"
