apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: tfc-agent
  name: tfc-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: tfc-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: tfc-agent
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - /home/tfc-agent/bin/tfc-agent
          env:
            - name: TFC_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: tfc-agent-token
            - name: KUBE_LOAD_CONFIG_FILE
              value: "false"
          image: olfi01/custom-tfc-agent:latest
          name: agent
          resources:
            limits:
              memory: 4G
              cpu: "1"
            requests:
              memory: 2G
              cpu: "250m"
      serviceAccountName: tfc-agent
