apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  acme:
    email: flommeyer@gmail.com
    privateKeySecretRef:
      name: step-ca
    server: https://step-ca.fritz.box/acme/acme/directory
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3ekNDQVdtZ0F3SUJBZ0lRSkE0cnREN1Q1cWd3eGJQcklQRkxIekFLQmdncWhrak9QUVFEQWpCQU1Sb3cKR0FZRFZRUUtFeEZFWVhOSVpXbHpkRUZ3WVhKMGJXVnVkREVpTUNBR0ExVUVBeE1aUkdGelNHVnBjM1JCY0dGeQpkRzFsYm5RZ1VtOXZkQ0JEUVRBZUZ3MHlOREEyTVRFeE9ETTFNalphRncwek5EQTJNRGt4T0RNMU1qWmFNRUF4CkdqQVlCZ05WQkFvVEVVUmhjMGhsYVhOMFFYQmhjblJ0Wlc1ME1TSXdJQVlEVlFRREV4bEVZWE5JWldsemRFRncKWVhKMGJXVnVkQ0JTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUV6NFpOK0tQbwo5aUs1NDBML0lodldtTW0xd3pKZEZpbGVwT1BRWnNDUkJpd2RtM0w1YVk5NU1kV2UrQWNpdTROVU5Cc3BwUzl2Ck93cGxoeUVsV3BuNHY2TkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFFd0hRWURWUjBPQkJZRUZNTTZQa3ZJdHk1aEJMTThBdnRvWEFPLzhjWlVNQW9HQ0NxR1NNNDlCQU1DQTBnQQpNRVVDSUIyMUs1S0E5K3hkU2FCcmpIRHRwb2tWdksrSGtvVEMrUkRPcDRSTWNSd05BaUVBNnhYbnBOVmV5ejhaCkNsWXJja2Z1ZEN0U3ZTYWhKWG90cmFpZ0FmNXdjcXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
            ingressTemplate:
              metadata:
                annotations:
                  nginx.org/mergeable-ingress-type: minion
