apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: actions-runner-system
    name: in-cluster
  sources:
    - repoURL: "https://actions-runner-controller.github.io/actions-runner-controller"
      chart: actions-runner-controller
      targetRevision: 0.23.7
      helm:
        releaseName: actions-runner-controller
        values: |
          githubWebhookServer:
            enabled: true
    - repoURL: "https://github.com/DasHeistApartment/servah-gitops"
      targetRevision: HEAD
      path: actions-runner-controller
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
