apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: actions-runner-system
    name: in-cluster
  source:
    repoURL: "ghcr.io/actions/actions-runner-controller-charts"
    chart: gha-runner-scale-set-controller
    targetRevision: 0.9.2
    helm:
      releaseName: actions-runner-controller
      values: |
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        githubConfigSecret: github-pat
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
