apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dex
    name: in-cluster
  sources:
    - repoURL: "https://github.com/DasHeistApartment/servah-gitops"
      targetRevision: HEAD
      path: dex
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
