apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: arc-systems
    name: in-cluster
  sources:
    - repoURL: "ghcr.io/actions"
      chart: actions-runner-controller-charts/gha-runner-scale-set-controller
      targetRevision: 0.13.0
      helm:
        releaseName: arc
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
