apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imcode-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: imcode
    name: in-cluster
  source:
    path: imcode-server
    repoURL: "https://github.com/DasHeistApartment/servah-gitops"
    targetRevision: HEAD
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
