apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-static-provisioner
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
  source:
    path: local-static-provisioner
    repoURL: "https://github.com/DasHeistApartment/servah-gitops"
    targetRevision: HEAD
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
