apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: palworld-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: palworld
  source:
    path: palworld-server
    repoURL: "https://github.com/DasHeistApartment/servah-gitops"
    targetRevision: HEAD
  project: palworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
