apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-ca
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: smallstep
    name: in-cluster
  source:
    repoURL: "https://smallstep.github.io/helm-charts/"
    chart: step-certificates
    targetRevision: 1.26.1
    helm:
      releaseName: step-certificates
      values: |
        ca:
          db:
            existingClaim: database-step-ca
  project: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
