# To mount the disk created by terraform:
# `sudo fdisk -l`` to find out name of drive (usually /dev/sdb)
# `sudo fdisk [diskName]`
# n (new partition)
# p (primary partition)
# accept defaults for partition number, first sector and last sector
# w (write)
# `sudo mkfs -t ext4 [diskName]1`
# Retrieve UUID from output of previous command
# `export UUID='[UUID]'`
# `sudo mkdir -p /mnt/disks/ark`
# `sudo chmod -R 777 /mnt/disks/ark`
# `sudo tee -a "/etc/fstab" > /dev/null <<EOF
# # ARK disk, manually added
# /dev/disk/by-uuid/$UUID /mnt/disks/ark ext4 defaults 0 2
# EOF`

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ark-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.volumes.storageClassName }}
  local:
    path: /mnt/disks/ark
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node-0