apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
data:
  nginx.conf: |
    events { }

    http {

      server {
        listen 8080;
        server_name proxmox.crazypokemondev.de;
        
        location / {
          proxy_pass https://servah-host.fritz.box:8006;
        }
      }

      server {
        listen 8080;
        server_name dynmap.hermelincraft.crazypokemondev.de;
        
        location / {
          proxy_pass http://flommc.fritz.box:8102;
        }
      }
      
      server {
        listen 8080;
        server_name smarthome.crazypokemondev.de;

        proxy_buffering off;

        location / {
          proxy_pass http://homeassistant.fritz.box:8123;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
        }
      }
    }
