apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  template:
    spec:
      organization: {{ .Values.organization }}
      {{- with .Values.labels }}
      labels: 
        {{- toYaml . | nindent 8 }}
      {{- end }}